#  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib_sequence(n, first, second):
    """Returns a list of terms in the Fib sequence up to the value n, beginning with first and second."""
    if (first + second) > n:
        return [first, second]
    else:
        return [first] + fib_sequence(n, second, first + second)

def solution():
    print(sum(n for n in fib_sequence(4000000, 1, 2) if not n % 2))

if __name__ == '__main__':
    solution()


