"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import time

def triangles():
    i = 1
    while True:
        yield sum(range(i+1))
        i += 1

def num_factors(n):
    return sum(2 for i in range(1, int(n**0.5 + 1)) if not n % i)

def solution():
    for n in triangles():
        if num_factors(n) >= 500:
            return n

if __name__ == '__main__':
    now = time.time()
    sol = solution()
    print("answer {0} found in {1} seconds".format(sol,  time.time() - now))
